services:
  frontend:
    image: agdevx/cart-frontend:latest
    networks:
      - agdevx-internal-docker-network
    restart: unless-stopped

  backend:
    image: agdevx/cart-backend:latest
    env_file: .env
    volumes:
      - ${CART_DB_PATH:?Set CART_DB_PATH in .env}:/app/data
    networks:
      - agdevx-internal-docker-network
    restart: unless-stopped

networks:
  agdevx-internal-docker-network:
    external: true
