services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
      - ./credentials.json:/etc/cloudflared/credentials.json:ro
    networks:
      - agdevx-internal-docker-network
    restart: unless-stopped

networks:
  agdevx-internal-docker-network:
    external: true
